### ISSUE TITLE
Doesn't synthesize with UTAU

### ISSUE THREAD

**Issue by kbinani** [cadencii/cadencii#4]
### Environment
- Cadencii version 3.5.3
- .NET Framework version: unknown
- UTAU version: 0.4.18
- VoiceDB: デフォルト
### How to reproduce
1. Launch Cadencii.
2. Change track renderer to UTAU
3. Put a note with lyric "あ".
4. Press "play" button. => Synthesize will complete, but no sound.

**Comment by Woolton** [comment]
Hello, I am getting no audio still
